name: alibc
version: 1.0.4
homepage: https://github.com/hackett0/alibc
description: >
  阿里百川SDK For Flutter.

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.hackett.alibc
        pluginClass: AlibcPlugin
      ios:
        pluginClass: AlibcPlugin