name: alibc
version: 1.0.7
homepage: https://github.com/hackett0/alibc
description: >
  阿里百川SDK For Flutter.

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.hackett.alibc
        pluginClass: AlibcPlugin
      ios:
        pluginClass: AlibcPlugin